### ISSUE TITLE
Image replication from Quay.io finished successfully but containers are not downloaded

### ISSUE THREAD

**Issue by danielnbalasoiu** [goharbor/harbor#11323]
**Expected behavior and actual behavior:**
Expected behavior: `prometheus:latest` image should be downloaded into library after replication job finished with **SUCCESS**.
Actual behavior: Empty library. No container images.

**Steps to reproduce the problem:**
1. Go to [quay.io](https://quay.io) and create an account (if you don't have one)
2. Go to **Account Settings** - **Robot Accounts** and create a **New Robot Account**
3. Go to **Administration** - **Registries** - **NEW ENDPOINT**
4. Go to Harbor and create a **New Registry Endpoint** with the following details:
- **Provider**: `quay.io`
- **Name**: `q`
- **Endpoin URL**: `https://quay.io/`
- **Access ID**: [robot-account-id]
- **Access Secret**:  [robot-account-secret]
- Check **Verify Remote Cert** box
- **TEST CONNECTION**
- Hit **OK** button if connection is successful. If not, check credential details again.
5. Go to  **Administration** - **Replications** and add a *NEW REPLICATION RULE** with the following details:
- **Name**: `quay-prometheus`
- **Source registry**: Select `q-https://quay.io/` from the drop-down menu
- **Source resource filter**:
  - **Name**: `prometheus`
  - **Tag**: `latest`
- **Trigger Mode**: `Manual`
- Check `Override` box
- Check `Enable rule` box and save
6. Hit **REPLICATE** button and confirm replication. Replication job status should be listed in the **Executions** table. (it will display **SUCCESS**)
7. Click on the **ID** of the job to go to **EXECUTION** page and check job's details.
Expected result:
`SUCCESS`: `1` 
`FAILURE`: `0` 
`IN PROGRESS`: `0` 
`STOPPED`: `0` 

Actual result:
`SUCCESS`: `0` 
`FAILURE`: `0` 
`IN PROGRESS`: `0` 
`STOPPED`: `0` 

**Versions:**
Please specify the versions of following systems.

- harbor version: `v1.10.1-f3e11715`
- docker engine version: `19.03.5`
- docker-compose version: `1.25.1, build a82fef0`

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
```yaml
hostname: harbor.mylab.com

http:
  port: 80

harbor_admin_password: [redacted]

database:
  password: [redacted]
  max_idle_conns: 50
  max_open_conns: 100

data_volume: /data

clair:
  updaters_interval: 12

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

_version: 1.10.0
```

- **Log files:** You can get them by package the `/var/log/harbor/` .
[jobservice.log](https://github.com/goharbor/harbor/files/4389474/jobservice.log)
[chartmuseum.log](https://github.com/goharbor/harbor/files/4389475/chartmuseum.log)

**Comment by punycode** [comment]
I was actually interested in this bug myself. While looking how to fix this on a `1.10.1` checkout, I realized, that the fix already has found it's way into master.

The reason this was happening, is that Quay.io has a default pagination built into the `/v2/<name>/tags/list` endpoint. To deal with this, the pagination protocol in [Listing Image Tags](https://docs.docker.com/registry/spec/api/#listing-image-tags) has to be followed. From what I am seeing, current `master` has already rewritten the implementation, to follow such links: https://github.com/goharbor/harbor/blob/master/src/pkg/registry/client.go#L196

Bug should could therefore be closed with the next release from `master`.

**Comment by bjethwan** [comment]
I am facing this too....Is this out in Harbor v1.10.2?

**Comment by bitsf** [comment]
yes, we have fixed issues about page problem. you can verify with a newer release.

**Comment by xaleeks** [comment]
please let us know if you're still coming across this issue

**Comment by qw3r3wq** [comment]
version 2.5.3 still cannot get all images from https://quay.io/tripleoussuri/**

**Comment by JamesOBenson** [comment]
I had the same issue on v2.4 and v2.7 with openstack images, replicating this: `https://quay.io/organization/openstack.kolla/**` . I get a success message, but with zero replications. If I specify a specific image, like `https://quay.io/organization/openstack.kolla/fluentd` can successfully download the image.

**Comment by qw3r3wq** [comment]
> I had the same issue on v2.4 and v2.7 with openstack images, replicating this: `https://quay.io/organization/openstack.kolla/**` . I get a success message, but with zero replications. If I specify a specific image, like `https://quay.io/organization/openstack.kolla/fluentd` can successfully download the image.

Did you solve it somehow?

**Comment by JamesOBenson** [comment]
From what I understand there is no way to solve this for fuzzy matching without creating an account. The resolution is to create an account on quay, then it will sync properly, otherwise it will have to be one at a time.

See this thread: https://github.com/goharbor/harbor/issues/12797

**Comment by qw3r3wq** [comment]
> From what I understand there is no way to solve this for fuzzy matching without creating an account. The resolution is to create an account on quay, then it will sync properly, otherwise it will have to be one at a time.
> 
> See this thread: #12797

Hm, I have quay.io account, but it is not part of tripleo namespace, so I end up in same situation, I will check the thread
