### ISSUE TITLE
Harbor 2.2.0-rc1 upgrade - harbor-core container fails to start with dirty database version 50 error

### ISSUE THREAD

**Issue by troy256** [goharbor/harbor#14191]
**Expected behavior and actual behavior:**
Attempted to upgrade from 2.1.1 to 2.2.0-rc1.  Harbor-core container in restart loop and unable to connect to web UI.  Log file /var/log/harbor/core.log shows:

`[FATAL] [/core/main.go:188]: failed to migrate: Dirty database version 50. Fix and force version.`

How do I fix?

- harbor version: 2.2.0-rc1
- docker engine version: 19.03.12
- docker-compose version: 1.25.5, build 8a1c60f6

**Comment by bitsf** [comment]
check /var/log/harbor/core.log, find why first error message that db upgrade failed

**Comment by bitsf** [comment]
please rollback db, and wait for 2.2.0-rc2 release

**Comment by troy256** [comment]
I see this repeated in core.log:

```
[INFO] [/common/dao/base.go:65]: Registering database: type-PostgreSQL host-postgresql port-5432 database-registry sslmode-"disable"
[INFO] [/common/dao/base.go:70]: Register database completed
[INFO] [/common/dao/pgsql.go:127]: Upgrading schema for pgsql ...
[ERROR] [/common/dao/pgsql.go:132]: Failed to upgrade schema, error: "Dirty database version 50. Fix and force version."
[FATAL] [/core/main.go:188]: failed to migrate: Dirty database version 50. Fix and force version.
```

**Comment by ywauthy** [comment]
Same here when trying to upgrade from 2.1.0 to the last 2.2.0.

**Comment by tomhouweling1987** [comment]
Same here when trying to upgrade from 2.1.3 to 2.2.0

**Comment by StevenLeiZhang** [comment]
I hit the same issue, when I fresh install harbor 2.2.0 with helm.
After investigaion , I found the root cause is the version of postgresql. My postgresql version is 9.5, harbor's migration runs some sql that the posgersql version can not support.

My Error msg is Dirty database version 40. Fix and force version
As what is mentioned in postgresql doc https://github.com/golang-migrate/migrate/blob/master/FAQ.md#what-does-dirty-database-mean.
This error means migration failed at v40.

So I checkout source code of Harbor, there are sone sql files under make/migrations/postgresql. I find a file named 0040_2.1.1_schema.up.sql.  the first sql in this file is "ALTER TABLE project ADD COLUMN IF NOT EXISTS registry_id int;"

I connect postgresql with postgresql client and run this sql, it returns 
"
ERROR:  syntax error at or near "NOT"
LINE 1: ALTER TABLE project ADD COLUMN IF NOT EXISTS registry_id int...
"
I remove " IF NOT EXISTS", and re-run it, this sql works. So I think that is the reason why my migrations stops at v40.


My solution:
I remove all the " IF NOT EXISTS" of "ALTER TABLE " ,   manually run all the sql in file "0040_2.1.0_shcema.up.sql" and "0050_2.2.0_schema.up.sql". and manually set the value of table schema_migrations as below:

registry=> select * from schema_migrations;
 version | dirty 
---------+-------
      50 | f


All my pods works now!!!!!

Please use one postgresql with higher version. If you can not install high version postgresql, you could try my solution.

**Comment by chaospuppy** [comment]
Is this actually resolved by upgrading to 2.2.1?  There's nothing in the [release notes](https://github.com/goharbor/harbor/issues?q=is%3Aissue+label%3Atarget%2F2.1.5+is%3Aclosed) for any of the releases made since 2.2.1-rc1 that mentions a resolution for this.

**Comment by ywauthy** [comment]
I tried to upgrade from 2.1.0 to 2.2.1 and still have the same issue.  
```bash
[ERROR] [/common/dao/pgsql.go:132]: Failed to upgrade schema, error: "Dirty database version 50. Fix and force version."
[FATAL] [/core/main.go:188]: failed to migrate: Dirty database version 50. Fix and force version.
```
@chaospuppy So no it's still not resolved.

**Comment by chaospuppy** [comment]
Thank you for the info @ywauthy !

**Comment by hemantdindi** [comment]
Same with us as well. Tried to upgrade to v2.2.1 from v2.0.1.
```
Apr 24 13:03:21 172.29.0.1 core[18086]: 2021-04-24T11:03:21Z [ERROR] [/common/dao/pgsql.go:132]: Failed to upgrade schema, error: "Dirty database version 50. Fix and force version."
Apr 24 13:03:21 172.29.0.1 core[18086]: 2021-04-24T11:03:21Z [FATAL] [/core/main.go:188]: failed to migrate: Dirty database version 50. Fix and force version.
```

**Comment by hemantdindi** [comment]
I tried to run the schema query manually - 
```
https://github.com/goharbor/harbor/blob/v2.2.1/make/migrations/postgresql/0050_2.2.0_schema.up.sql
```
The error was in line 34
```
DO $$
DECLARE
    art RECORD;
    art_size integer;
BEGIN
    FOR art IN SELECT * FROM artifact WHERE size = 0
    LOOP
      SELECT sum(size) INTO art_size FROM blob WHERE digest IN (SELECT digest_blob FROM artifact_blob WHERE digest_af=art.digest);
      UPDATE artifact SET size=art_size WHERE id = art.id;
    END LOOP;
END $$;
```
By changing art_size to bigint, the sqlfile got executed. Also updated the table schema_migrations;
|version | dirty|
|---------|-------|
|51 | f|

**Comment by baoroushi** [comment]
I hit the same issue, when I fresh install harbor 2.7.0 with helm.
`2023-01-12T07:46:35Z [INFO] [/common/dao/base.go:72]: Register database completed
2023-01-12T07:46:35Z [INFO] [/common/dao/pgsql.go:135]: Upgrading schema for pgsql ...
2023-01-12T07:46:35Z [ERROR] [/common/dao/pgsql.go:140]: Failed to upgrade schema, error: "Dirty database version 40. Fix and force version."
2023-01-12T07:46:35Z [FATAL] [/core/main.go:179]: failed to migrate the database, error: Dirty database version 40. Fix and force version.
`
