### ISSUE TITLE
error upgrade from v1.10.0 to v.2.2.0

### ISSUE THREAD

**Issue by zyitingftnt** [goharbor/harbor#15066]
I ran into issue when executing the command referred in harbor documentation to upgrade from 1.10.0 to 2.2.0

the Harbor 1.10.0 works well with below files

**[root@Lab /]# ls -al /harbor.v1.10.0/**
total 629916
drwxr-xr-x.  3 root root       158 Jun  4 00:21 .
dr-xr-xr-x. 21 root root      4096 Jun  4 09:26 ..
drwxr-xr-x.  3 root root        20 Jun  4 00:21 common
-rw-r--r--.  1 root root      3398 Dec  5  2019 common.sh
-rw-r--r--.  1 root root      7291 Jun  4 00:21 docker-compose.yml
-rw-r--r--.  1 root root 644985680 Dec  5  2019 harbor.v1.10.0.tar.gz
-rw-r--r--.  1 root root      5756 Jun  4 00:18 harbor.yml
-rwxr-xr-x.  1 root root      2284 Dec  5  2019 install.sh
-rw-r--r--.  1 root root     11347 Dec  5  2019 LICENSE
-rwxr-xr-x.  1 root root      1749 Dec  5  2019 prepare

Below are files out-of-box for v2.2.0
**[root@Lab /]# tree /harbor**
/harbor
├── common.sh
├── harbor.v2.2.0.tar.gz
├── harbor.yml.tmpl
├── install.sh
├── LICENSE
└── prepare

**[root@Lab /]# docker run -it --rm -v /:/hostfs goharbor/prepare:v2.2.0 migrate -i /harbor.v1.10.0/harbor.yml**
migrating to version 2.0.0
migrating to version 2.1.0
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/migrate.py", line 43, in migrate
    m.migrate(current_input_path, current_output_path)
  File "/usr/src/app/migrations/version_2_1_0/__init__.py", line 30, in migrate
    f.write(tpl.render(**config_dict))
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/src/app/migrations/version_2_1_0/harbor.yml.jinja", line 376, in top-level template code
    host: {{ external_redis.host }}:{{ external_redis.port }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'port'

**And this is content of existing v1.10.0 harbor.yml**
hostname: XXXXXXXXXXXXXX
http:
  port: 80
https:
  port: 443
  certificate: XXXXXXXXXXXXXX.crt
  private_key: XXXXXXXXXXXXXX.key
harbor_admin_password: XXXXXXXXXXXXXX
database:
  password: XXXXXXXXXXXXXX
  max_idle_conns: 50
  max_open_conns: 100
data_volume: /harbor_data
clair:
  updaters_interval: 12
jobservice:
  max_job_workers: 10
notification:
  webhook_job_max_retry: 10
chart:
  absolute_url: disabled
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

_version: 1.10.0

external_database:
  harbor:
    host: XXXXXXXXXXXXXX
    port: 5432
    db_name: registry
    username: XXXXXXXXXXXXXX
    password: XXXXXXXXXXXXXX
    ssl_mode: disable
    max_idle_conns: 50
    max_open_conns: 1024
  clair:
    host: XXXXXXXXXXXXXX
    port: 5432
    db_name: postgres
    username: XXXXXXXXXXXXXX
    password: XXXXXXXXXXXXXX
    ssl_mode: disable
  notary_signer:
    host: XXXXXXXXXXXXXX
    port: 5432
    db_name: notarysigner
    username: XXXXXXXXXXXXXX
    password: XXXXXXXXXXXXXX
    ssl_mode: disable
  notary_server:
    host: XXXXXXXXXXXXXX
    port: 5432
    db_name: notaryserver
    username: XXXXXXXXXXXXXX
    password: XXXXXXXXXXXXXX
    ssl_mode: disable

external_redis:
  host: XXXXXXXXXXXXXX
  port: 6379
  password: XXXXXXXXXXXXXX
  registry_db_index: 1
  jobservice_db_index: 2
  chartmuseum_db_index: 3
  clair_db_index: 4

proxy:
  http_proxy: 
  https_proxy: 
  no_proxy: 127.0.0.1,localhost,.local,.internal,log,db,redis,nginx,core,portal,postgresql,jobservice,registry,registryctl,clair,chartmuseum,notary-server
  components:
    - core
    - jobservice
    - clair

**Comment by ninjadq** [comment]
it already fixed in https://github.com/goharbor/harbor/pull/14312. Need cherry-pick to 2.2

**Comment by ninjadq** [comment]
as a workaround, you can use a newer version of `goharbor/prepare:v2.3.0-rc1`.
Or you can wait for the stable release like  `goharbor/prepare:2.2.3` or  `goharbor/prepare:2.3.0`

**Comment by zyitingftnt** [comment]
@ninjadq I tried the v2.3.0-rc1, still the same:

# docker image ls
REPOSITORY                      TAG                IMAGE ID       CREATED      SIZE
goharbor/harbor-exporter        v2.3.0-build.695   bff6610fa302   7 days ago   81MB
goharbor/chartmuseum-photon     v2.3.0-build.695   62e6d893f07b   7 days ago   178MB
goharbor/redis-photon           v2.3.0-build.695   19b4ee4c6a8e   7 days ago   190MB
goharbor/trivy-adapter-photon   v2.3.0-build.695   45db9053c04c   7 days ago   164MB
goharbor/notary-server-photon   v2.3.0-build.695   8146e21ba66b   7 days ago   105MB
goharbor/notary-signer-photon   v2.3.0-build.695   b10b3cd78601   7 days ago   102MB
goharbor/harbor-registryctl     v2.3.0-build.695   8f7eb7063137   7 days ago   132MB
goharbor/registry-photon        v2.3.0-build.695   4ccff440300f   7 days ago   81MB
goharbor/nginx-photon           v2.3.0-build.695   403089dc8928   7 days ago   44MB
goharbor/harbor-log             v2.3.0-build.695   4b3b311f46a5   7 days ago   194MB
goharbor/harbor-jobservice      v2.3.0-build.695   bcb7a722eb0b   7 days ago   170MB
goharbor/harbor-core            v2.3.0-build.695   79cac4ab64de   7 days ago   157MB
goharbor/harbor-portal          v2.3.0-build.695   400fcd207328   7 days ago   57.3MB
goharbor/harbor-db              v2.3.0-build.695   a029a49969f6   7 days ago   262MB
goharbor/prepare                v2.3.0-build.695   **d6d30226179b**   7 days ago   291MB


# docker run -it --rm -v /:/hostfs **d6d30226179b** migrate -i /harbor/harbor.yml.v1.10.0
migrating to version 2.0.0
migrating to version 2.1.0
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/migrate.py", line 43, in migrate
    m.migrate(current_input_path, current_output_path)
  File "/usr/src/app/migrations/version_2_1_0/__init__.py", line 30, in migrate
    f.write(tpl.render(**config_dict))
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/src/app/migrations/version_2_1_0/harbor.yml.jinja", line 376, in top-level template code
    host: {{ external_redis.host }}:{{ external_redis.port }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'port'


# cat /harbor.v1.10.0/harbor.yml | grep -v "#"| grep -v "^$"
hostname: XXXXX
http:
  port: 80
https:
  port: 443
  certificate: /harbor_data/certs/XXXXX.crt
  private_key: /harbor_data/certs/XXXXX.key
harbor_admin_password: XXXXX
database:
  password: XXXXX
  max_idle_conns: 50
  max_open_conns: 100
data_volume: /harbor_data
clair:
  updaters_interval: 12
jobservice:
  max_job_workers: 10
notification:
  webhook_job_max_retry: 10
chart:
  absolute_url: disabled
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor
_version: 1.10.0
external_database:
  harbor:
    host: XXXXX
    port: 5432
    db_name: registry
    username: XXXXX
    password: XXXXX
    ssl_mode: disable
    max_idle_conns: 50
    max_open_conns: 1024
  clair:
    host: XXXXX
    port: 5432
    db_name: postgres
    username: XXXXX
    password: XXXXX
    ssl_mode: disable
  notary_signer:
    host: XXXXX
    port: 5432
    db_name: notarysigner
    username: XXXXX
    password: XXXXX
    ssl_mode: disable
  notary_server:
    host: XXXXX
    port: 5432
    db_name: notaryserver
    username: XXXXX
    password: XXXXX
    ssl_mode: disable
external_redis:
  host: XXXXX
  port: 6379
  password: XXXXX
  registry_db_index: 1
  jobservice_db_index: 2
  chartmuseum_db_index: 3
  clair_db_index: 4
proxy:
  http_proxy: 
  https_proxy: 
  no_proxy: 127.0.0.1,localhost,.local,.internal,log,db,redis,nginx,core,portal,postgresql,jobservice,registry,registryctl,clair,chartmuseum,notary-server
  components:
    - core
    - jobser
