### ISSUE TITLE
Tag retention mark untagged images as IMMUTABLE

### ISSUE THREAD

**Issue by baby-gnu** [goharbor/harbor#16335]
Hello.

In our harbor `v2.3.2-6b6c21da`, we setup the following tag retention policy:

- For the repositories matching `**`, retain always with tags matching `[0-9]*.[0-9]*.[0-9]*,v[0-9]*.[0-9]*.[0-9]*,pp-[0-9]*`, to keep semantic-release versions (with or without a `v` prefix)
- For the repositories matching `**`, retain always with tags matching `dev,testing,latest,stable`, to keep moving tags even if they don't point to a semantic-release version (dev and testing mostly)
- For the repositories matching `**`, retain the most recently pushed `5` artifacts with tags matching `**` with `untagged`

Then, we setup a tag immutability policy:

- For the repositories matching `**`, tags matching `[0-9]*.[0-9]*.[0-9]*,v[0-9]*.[0-9]*.[0-9]*`, for semantic-release versions (with or without a `v` prefix)

<details><summary>all digests without tags are marked <code>IMMUTABLE</code></summary>

```
|                                 Digest                                  |                           Tag                            | Kind  | Labels |     PushedTime      |     PulledTime      |     CreatedTime     | Retention |
|-------------------------------------------------------------------------|----------------------------------------------------------|-------|--------|---------------------|---------------------|---------------------|-----------|
| sha256:8c6419acef78f10a6835cc6bbf784771788d9f515c9ba6e3d1540e7da3d69c3f | 34-create-modal-for-add-app-in-pack-edition,git-966437c1 | image |        | 2022/02/08 10:28:15 | 2022/02/08 10:28:17 | 2022/02/08 10:27:58 | RETAIN    |
| sha256:da901a8bf90b5042e6a0cdf37957a23ac4938d223bc9414e64c099db774c0221 | dev                                                      | image |        | 2022/02/08 09:14:16 | 2022/02/08 09:14:21 | 2022/02/08 09:13:53 | RETAIN    |
| sha256:49c6a078a3bcad78ffb88561627a5a800ed706c24bedd12e25390730bf661ac3 | 28-refactor-pack-page-front,git-10a76c29                 | image |        | 2022/02/08 08:49:24 | 2022/02/08 08:49:29 | 2022/02/08 08:49:02 | RETAIN    |
| sha256:ae74f5f7f751545097773c8a2821f4adfb25cb864c5f40617c402b74347bca1d | 26-refactor-index-page-front,git-0c29e193                | image |        | 2022/02/08 08:43:50 | 2022/02/08 08:43:55 | 2022/02/08 08:43:32 | RETAIN    |
| sha256:b5d6eee49349a6f99b82d618c0fc810535c4002c07cce97b90808154f2038fdb | git-0998e8e8                                             | image |        | 2022/02/08 08:31:00 | 2022/02/08 08:31:29 | 2022/02/08 08:31:00 | RETAIN    |
| sha256:efc5059f50905b925298677446469f7ebcfdd204ffec0d5a82ba7164920ec4bc | git-f5a9d811                                             | image |        | 2022/02/07 16:31:28 | 2022/02/07 16:31:48 | 2022/02/07 16:31:28 | DEL       |
| sha256:69a7096e1875758057860dc1ded7d09c6becdddb2efd84936ea44145c6456d8d | git-b4845dde                                             | image |        | 2022/02/07 16:17:53 | 2022/02/07 16:18:14 | 2022/02/07 16:17:53 | DEL       |
| sha256:136489a1fb03cd977b94610598d93220852a983ddb6e96ef82b2ad24e47dfc14 | git-2da58c85                                             | image |        | 2022/02/07 15:57:08 | 2022/02/07 15:57:26 | 2022/02/07 15:57:08 | DEL       |
| sha256:e1461786936d6e33769c240fa2726aa7c7cbe924c85241ee63b3a9386301adab |                                                          | image |        | 2022/02/07 15:29:58 | 2022/02/07 15:30:23 | 2022/02/07 15:29:58 | IMMUTABLE |
| sha256:6cb8fb359b4969d72cc69ce0b91e4ccbad4959749cabf165c28822bb733e1b06 |                                                          | image |        | 2022/02/07 14:13:03 | 2022/02/07 14:13:20 | 2022/02/07 14:13:03 | IMMUTABLE |
| sha256:299a92c5e3519dbfd6ca62c5a89ac683f24c42de9216ff9aa90e2ce4c3322037 |                                                          | image |        | 2022/02/07 09:55:53 | 2022/02/07 09:56:13 | 2022/02/07 09:55:53 | IMMUTABLE |
| sha256:66736080651eb61953e358dc282d9d496f81331fbb4571bbfd3bb962d768e516 |                                                          | image |        | 2022/02/07 09:14:42 | 2022/02/07 09:15:06 | 2022/02/07 09:14:42 | IMMUTABLE |
| sha256:f16a8b125e80c2d69d1f575679e4bba8c164b5a95e6d2dfb9e9bf73dbfd2d66b |                                                          | image |        | 2022/02/04 15:01:32 | 2022/02/04 15:01:54 | 2022/02/04 15:01:32 | IMMUTABLE |
| sha256:b2f58ef920a79a89c511d1474fe389a596fbfc46f2a8086fc8e2dde4bd402e3d |                                                          | image |        | 2022/02/04 13:44:55 | 2022/02/04 13:45:11 | 2022/02/04 13:44:55 | IMMUTABLE |
| sha256:8dc7be0e18f9ccf1bd397c6001736abb55c72c49991ad91600cdb5e24bf6a8eb |                                                          | image |        | 2022/02/04 10:41:27 | 2022/02/04 10:41:49 | 2022/02/04 10:41:27 | IMMUTABLE |
| sha256:20753f37fd80874dca542fec9bfe51a71bb3b93abc69c6d827e0f1f9b9293569 |                                                          | image |        | 2022/02/04 09:28:36 | 2022/02/04 09:28:42 | 2022/02/04 09:28:36 | IMMUTABLE |
```
</details>

<details><summary>When I temporary disable the tag immutability and execute a dry run, untagged digest are marked for deletion</summary>

```
|                                 Digest                                  |                           Tag                            | Kind  | Labels |     PushedTime      |     PulledTime      |     CreatedTime     | Retention |
|-------------------------------------------------------------------------|----------------------------------------------------------|-------|--------|---------------------|---------------------|---------------------|-----------|
| sha256:8c6419acef78f10a6835cc6bbf784771788d9f515c9ba6e3d1540e7da3d69c3f | 34-create-modal-for-add-app-in-pack-edition,git-966437c1 | image |        | 2022/02/08 10:28:15 | 2022/02/08 10:28:17 | 2022/02/08 10:27:58 | RETAIN    |
| sha256:da901a8bf90b5042e6a0cdf37957a23ac4938d223bc9414e64c099db774c0221 | dev                                                      | image |        | 2022/02/08 09:14:16 | 2022/02/08 09:14:21 | 2022/02/08 09:13:53 | RETAIN    |
| sha256:49c6a078a3bcad78ffb88561627a5a800ed706c24bedd12e25390730bf661ac3 | 28-refactor-pack-page-front,git-10a76c29                 | image |        | 2022/02/08 08:49:24 | 2022/02/08 08:49:29 | 2022/02/08 08:49:02 | RETAIN    |
| sha256:ae74f5f7f751545097773c8a2821f4adfb25cb864c5f40617c402b74347bca1d | 26-refactor-index-page-front,git-0c29e193                | image |        | 2022/02/08 08:43:50 | 2022/02/08 08:43:55 | 2022/02/08 08:43:32 | RETAIN    |
| sha256:b5d6eee49349a6f99b82d618c0fc810535c4002c07cce97b90808154f2038fdb | git-0998e8e8                                             | image |        | 2022/02/08 08:31:00 | 2022/02/08 08:31:29 | 2022/02/08 08:31:00 | RETAIN    |
| sha256:efc5059f50905b925298677446469f7ebcfdd204ffec0d5a82ba7164920ec4bc | git-f5a9d811                                             | image |        | 2022/02/07 16:31:28 | 2022/02/07 16:31:48 | 2022/02/07 16:31:28 | DEL       |
| sha256:69a7096e1875758057860dc1ded7d09c6becdddb2efd84936ea44145c6456d8d | git-b4845dde                                             | image |        | 2022/02/07 16:17:53 | 2022/02/07 16:18:14 | 2022/02/07 16:17:53 | DEL       |
| sha256:136489a1fb03cd977b94610598d93220852a983ddb6e96ef82b2ad24e47dfc14 | git-2da58c85                                             | image |        | 2022/02/07 15:57:08 | 2022/02/07 15:57:26 | 2022/02/07 15:57:08 | DEL       |
| sha256:e1461786936d6e33769c240fa2726aa7c7cbe924c85241ee63b3a9386301adab |                                                          | image |        | 2022/02/07 15:29:58 | 2022/02/07 15:30:23 | 2022/02/07 15:29:58 | DEL       |
| sha256:6cb8fb359b4969d72cc69ce0b91e4ccbad4959749cabf165c28822bb733e1b06 |                                                          | image |        | 2022/02/07 14:13:03 | 2022/02/07 14:13:20 | 2022/02/07 14:13:03 | DEL       |
| sha256:299a92c5e3519dbfd6ca62c5a89ac683f24c42de9216ff9aa90e2ce4c3322037 |                                                          | image |        | 2022/02/07 09:55:53 | 2022/02/07 09:56:13 | 2022/02/07 09:55:53 | DEL       |
| sha256:66736080651eb61953e358dc282d9d496f81331fbb4571bbfd3bb962d768e516 |                                                          | image |        | 2022/02/07 09:14:42 | 2022/02/07 09:15:06 | 2022/02/07 09:14:42 | DEL       |
| sha256:f16a8b125e80c2d69d1f575679e4bba8c164b5a95e6d2dfb9e9bf73dbfd2d66b |                                                          | image |        | 2022/02/04 15:01:32 | 2022/02/04 15:01:54 | 2022/02/04 15:01:32 | DEL       |
| sha256:b2f58ef920a79a89c511d1474fe389a596fbfc46f2a8086fc8e2dde4bd402e3d |                                                          | image |        | 2022/02/04 13:44:55 | 2022/02/04 13:45:11 | 2022/02/04 13:44:55 | DEL       |
| sha256:8dc7be0e18f9ccf1bd397c6001736abb55c72c49991ad91600cdb5e24bf6a8eb |                                                          | image |        | 2022/02/04 10:41:27 | 2022/02/04 10:41:49 | 2022/02/04 10:41:27 | DEL       |
| sha256:20753f37fd80874dca542fec9bfe51a71bb3b93abc69c6d827e0f1f9b9293569 |                                                          | image |        | 2022/02/04 09:28:36 | 2022/02/04 09:28:42 | 2022/02/04 09:28:36 | DEL       |
```
</details>

I'm not sure if it's a bug or a bad configuration.

Regards.

**Comment by chlins** [comment]
As your third retention policy `For the repositories matching **, retain the most recently pushed 5 artifacts with tags matching ** with untagged`,  this policy will only retain recent 5 untagged artifacts and other untagged artifacts will be deleted.

**Comment by baby-gnu** [comment]
@chlins that what I thought but the `immutability policy` is getting in the way as disabling it make tag retention work as you described.

**Comment by jakuboskera** [comment]
same issue in version v2.2.2-56d7937f

**Comment by chlins** [comment]
If you enable the immutable policy, it will certainly mark all untagged artifact to `IMMUTABLE` as you configured, so the tag retention policy will not work as expect because the artifact has been protected by immutable policy. I think you could adjust your policies to avoid the conflict.

**Comment by baby-gnu** [comment]
@chlins It looks like I'm missing something here, my immutable policy should match only `repositories matching **, tags matching [0-9]*.[0-9]*.[0-9]*,v[0-9]*.[0-9]*.[0-9]*`, I don't see where the `untagged` artifacts are protected :thinking:

**Comment by chlins** [comment]
@baby-gnu Hi, I have reproduced the same issue also in harbor v2.4, I found it's a bug in the case of untagged artifact immutable policy as you described after go through the code, and I will fix it in the next release.

**Comment by baby-gnu** [comment]
Shouldn't the `target/2.5.0` set to this issue in addition to the pull request?

Otherwise, it does not show up in the [Full list of issues fixed in v2.5.0](https://github.com/goharbor/harbor/releases/tag/v2.5.0-rc1) link.

**Comment by chlins** [comment]
@baby-gnu Hi, this fix has been merged into 2.5 and my pull request also has the label 2.5.0, but not know why it not shown in the [Full list of issues fixed in v2.5.0](https://github.com/goharbor/harbor/releases/tag/v2.5.0-rc1).

**Comment by lindhe** [comment]
I'm on Harbor 2.5, yet we're facing this exact problem. Anyone else having the same issue still?

**Comment by paulux84** [comment]
Hi @chlins...we are on the release and we are facing the same issue. All untagged images are blocked from a single "exlude 'latest'" rule

**Comment by chlins** [comment]
> Hi @chlins...we are on the release v2.10.0-6abb4eab and we are facing the same issue. All untagged images are blocked from a single "exlude 'latest'" rule

@paulux84 Could you try to reproduce the issue in the demo environment? https://demo.goharbor.io/

**Comment by paulux84** [comment]
> > Hi @chlins...we are on the release v2.10.0-6abb4eab and we are facing the same issue. All untagged images are blocked from a single "exlude 'latest'" rule
> 
> @paulux84 Could you try to reproduce the issue in the demo environment? https://demo.goharbor.io/

@chlins done...here you can see the report https://demo.goharbor.io/api/v2.0/retentions/1/executions/6/tasks/6
in the immutable policy i've added the simple rule "all immutable exlude 'latest' tag" that makes immutable also untagged images

**Comment by paulux84** [comment]
@chlins ok...i'll do it
