### ISSUE TITLE
Can't add external scanner using https with skip certificate verification

### ISSUE THREAD

**Issue by Acmarr** [goharbor/harbor#18804]
- Version of docker engine: 20.10.23, build 7155243
- Version of docker-compose: 1.25.5, build 8a1c60f6
- Configuration files of [Harbor]: [harbor.txt](https://github.com/goharbor/harbor/files/11692520/harbor.txt)
- Log files in /var/log/harbor/: [harborlogs.zip](https://github.com/goharbor/harbor/files/11693195/harborlogs.zip)
- Harbor Version: Version v2.7.0-864aca34

I'm working on an adapter to connect an external scanner to Harbor following the spec given at https://github.com/goharbor/pluggable-scanner-spec. When attempting to add (or test connection) the new external scanner using https and skip certificate verification checked, harbor lists the endpoint as unreachable.

However, if I have an existing scanner entry and edit the URL to point to the https endpoint of my adapter I can save the entry. Shortly afterwards harbor will pull the metadata endpoint and flag the scanner as healthy. After this I can conduct scans as normal.

**Comment by becitsthere** [comment]
We use the IP address of the adapter. The adapter is functional if it can be added (by editing an existing entry), but when adding it as a new entry, harbor shows "bad certificate" when testing the connection. We use the self signed cert.

**Comment by zyyw** [comment]
Hi @Acmarr @becitsthere , I deployed an external harbor-scanner-trivy:
```
ubuntu@domain:~/go-workspace/src/github.com/aquasecurity/harbor-scanner-trivy$ sudo ./scanner-trivy
{"built_at":"unknown","commit":"none","level":"info","msg":"Starting harbor-scanner-trivy","time":"2023-06-12T09:27:47Z","version":"dev"}
{"addr":":8080","level":"warning","msg":"Starting API server without TLS","time":"2023-06-12T09:27:47Z"}
```
The IP of this external is, say 1.2.3.4

Adding a new record:
1. add a new endpoint `http://1.2.3.4:8080` as the endpoint of a new scanner registration. -> `Test passed` after clicking `TEST CONNECTION`
2. change the endpoint to `https://1.2.3.4:8080` with checkbox selected -> errors out with message saying `Ping: registration trivy-8080:https://1.2.3.4:8080 is unreachable`

Editing the existing default Trivy scanner record:
1. update the endpoint to `http://1.2.3.4:8080` -> `Test passed` after clicking `TEST CONNECTION`
2. update the endpoint to `https://1.2.3.4:8080` with `Skip certificate verification` checkbox selected -> `Ping: registration Trivy:https://1.2.3.4:8080 is unreachable`

In both cases, they are unreachable.

**Comment by Acmarr** [comment]
In our adapter's case
Adding a new record: Works the same as you described with trivy

But for the second case: 
Update an existing endpoint to https://our_adapter_ip:9443/endpoint with Skip certificate verification checkbox selected -> TEST CONNECTION -> Unreachable -> Click Save -> Wait -> Adapter shows metadata endpoint hit -> Refresh external scanners -> Status now Healthy

**Comment by becitsthere** [comment]
With "skip certificate verification" checked, https connection test still fails. Can you confirm this is a bug? I think this is the most basic function.

**Comment by becitsthere** [comment]
Can anyone take a look and confirm if this is issue? "Skip certificate verification" for external adapter doesn't seem to work. This should be a very basic function.

**Comment by becitsthere** [comment]
@zyyw I saw the case is assign to you. Do you have any insights on the issue?

**Comment by Acmarr** [comment]
Has there been any testing on this issue? Seems like the linked issue above is seeing the same result.

**Comment by becitsthere** [comment]
Is there anyone to look into this issue? This has nothing to do with Trivy. In general, "skip certificate validation" is not working.
