### ISSUE TITLE
GC history box field alignment issues

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#19031]
How can we help you?

Inconsistent field alignment when GC details are present.

<img width="1620" alt="image" src="https://github.com/goharbor/harbor/assets/31262637/e95ddf63-8b5b-4cc1-98d6-da1fe79940ef">

**Comment by AllForNothing** [comment]
Fixed by #19050

**Comment by YangJiao0817** [comment]
This issue still exists.
<img width="1422" alt="image" src="https://github.com/goharbor/harbor/assets/72076317/46333b6b-2457-42a5-9d54-f7b565579a39">
