### ISSUE TITLE
harbor installation: network between harbor dockers is not connected

### ISSUE THREAD

**Issue by HowHsu** [goharbor/harbor#20456]
Follow the official doc to install Harbor, but the network between docker instances seems not connected.
the detail install process is: `wget` the v2.10.2 tgz installer, then extract it, then comment the https part in harbor.yml, then `sudo ./install.sh`.
docker version: 26.1.3
docker-compose version: v2.27.0

output of `sudo docker-compose ps`
```
NAME                IMAGE                                 COMMAND                  SERVICE       CREATED          STATUS                             PORTS
harbor-core         goharbor/harbor-core:v2.10.2          "/harbor/entrypoint.…"   core          26 minutes ago   Up 44 seconds (health: starting)   
harbor-db           goharbor/harbor-db:v2.10.2            "/docker-entrypoint.…"   postgresql    26 minutes ago   Up 26 minutes (healthy)            
harbor-jobservice   goharbor/harbor-jobservice:v2.10.2    "/harbor/entrypoint.…"   jobservice    26 minutes ago   Up 4 seconds (health: starting)    
harbor-log          goharbor/harbor-log:v2.10.2           "/bin/sh -c /usr/loc…"   log           26 minutes ago   Up 26 minutes (healthy)            127.0.0.1:1514->10514/tcp
harbor-portal       goharbor/harbor-portal:v2.10.2        "nginx -g 'daemon of…"   portal        26 minutes ago   Up 26 minutes (healthy)            
nginx               goharbor/nginx-photon:v2.10.2         "nginx -g 'daemon of…"   proxy         26 minutes ago   Up 26 minutes (unhealthy)          0.0.0.0:80->8080/tcp, :::80->8080/tcp
redis               goharbor/redis-photon:v2.10.2         "redis-server /etc/r…"   redis         26 minutes ago   Up 26 minutes (healthy)            
registry            goharbor/registry-photon:v2.10.2      "/home/harbor/entryp…"   registry      26 minutes ago   Up 26 minutes (healthy)            
registryctl         goharbor/harbor-registryctl:v2.10.2   "/home/harbor/start.…"   registryctl   26 minutes ago   Up 26 minutes (healthy)     
```
proxy log:
```
May 20 11:51:33 instance-20240517-055402 proxy[6935]: 2024/05/20 11:51:33 [error] 7#0: *55 upstream timed out (110: Connection timed out) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://192.168.32.7:8080/", host: "localhost:8080"

```

core log:
```
May 20 11:52:31 instance-20240517-055402 core[6935]: 2024-05-20T11:52:31Z [INFO] [/core/main.go:142]: initializing cache ...
May 20 11:52:51 instance-20240517-055402 core[6935]: 2024-05-20T11:52:51Z [ERROR] [/lib/cache/cache.go:124]: failed to ping redis://redis:6379?idle_timeout_seconds=30, retry after 500ms : dial tcp 192.168.32.3:6379: i/o timeout


```

**Comment by stonezdj** [comment]
Please check your docker network settings, please do not use the 192.168.x.x for docker network, please refer https://serverfault.com/questions/916941/configuring-docker-to-not-use-the-172-17-0-0-range

**Comment by HowHsu** [comment]
Solved by reboot the server, it should be some issues with network policies not active.

**Comment by zoeczy** [comment]
> Please check your docker network settings, please do not use the 192.168.x.x for docker container network, it is easy to overlap with the host network, please refer https://serverfault.com/questions/916941/configuring-docker-to-not-use-the-172-17-0-0-range

Although we are not using the 192.168.x.x network, Redis connection timeout errors still occur, and restarting via Docker Compose does not resolve the issue.

> Jan 28 03:52:41 work1 core[18733]: 2026-01-28T03:52:41Z [ERROR] [/lib/cache/cache.go:124]: failed to ping redis://redis:6379?idle_timeout_seconds=30, retry after 500ms : dial tcp 10.10.1.3:6379: i/o timeout
