### ISSUE TITLE
Hide "popular repositories" by default

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#5380]
There's been constant concern about the "popular repositories".

Maybe we should disable it by default

**Comment by reasonerjt** [comment]
1) Add a flag to hide it and update permission of "top" API
2) Remove it.
Let's discuss with community how to implement.

**Comment by zhoumeina** [comment]
@reasonerjt , is backend flag ready yet?

**Comment by zhoumeina** [comment]
fixed by :#6061

**Comment by david-bascom-ihm** [comment]
I'm still seeing "popular repositories" when I navigate to https://github.com/my-company/.
How do I upload a js file to the portal to get rid of this section?

**Comment by rnhurt** [comment]
I too would like to remove the "popular repositories" from our corporate Github account. It's completely unnecessary and takes up a good portion of the screen, forcing valuable information below the fold.  Whoever thought it was a good idea to bring this back was very wrong.

**Comment by guy-roberts** [comment]
Came here because my repos are now below the fold

I know what I am looking for within our own organisation and don't need suggestions !

**Comment by ShaunGriffithRyff** [comment]
#metoo 

This is not a professional way to manage this. Anyone can create a "popular" repository with unprofessional name or description, and we have very little means to disable it's display.
