### ISSUE TITLE
Robot account expiration

### ISSUE THREAD

**Issue by ericvmw** [goharbor/harbor#6860]
In the current proposal for robot account, the robot account expiration is implicit and hard-coded. It would be useful to provide explicit expiration support on the API.

Client can specify the robot account validation period upon creation, which can be in hours / days. The get on a robot account can report the account validation info and status. This way the client app will have a better control of the robot account lifecycle. 

Robot account proposal references:
https://github.com/goharbor/community/pull/35
https://github.com/goharbor/harbor/issues/6565

**Comment by clouderati** [comment]
Hi @ericvmw – great idea. Is this something you're willing to contribute? I'm sure @ywk253100 would appreciate the help. :smile:

**Comment by wy65701436** [comment]
Done as PR https://github.com/goharbor/harbor/pull/7004 merged.

**Comment by muratzorer** [comment]
v1.10.1 API still does not support "expires_at" property on robot account creation. Do I missing something?
