### ISSUE TITLE
Set protocol of URL as "http" if it is not specified when creating the registry

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#7418]
branch replication_ng, commit fac0c2cc16cf8

after setup push_based replication, when doing docker push, failed to replication remote

error message:
Apr 17 17:32:11 172.22.0.1 core[1389]: 2019-04-17T09:32:11Z [ERROR] [controller.go:91]: the execution 1 failed: failed to do the prepare work for pushing/uploading resources: Post 10.192.216.134/api/projects: unsupported protocol scheme ""

**Comment by ywk253100** [comment]
Fixed.

**Comment by YakirShriker** [comment]
I got the same problem using harbor v2.1

Every replication to Harbor got error
2020-08-18T14:40:52Z [ERROR] [/replication/transfer/image/transfer.go:164]: Get me-dcr-k8s.int.liveperson.net/service/token?scope=repository%!A(MISSING)lpapps_release%!F(MISSING)lp-faastester-web%!A(MISSING)pull&service=harbor-registry: unsupported protocol scheme ""

**Comment by apannwitz** [comment]
I have installed the most recent version v.2.1.3 (via kubernetes helm chart) and still get the same error message. Any help?!

docker login -u <USER> <HARBORDOMAIN>
Password:
Error response from daemon: Get https://xxxxx.xxxxx.net/v2/: Get xxxxxx.xxxxxx.net/service/token?account=apannwitz&client_id=docker&offline_token=true&service=harbor-registry: unsupported protocol scheme ""

**Comment by homernajafi** [comment]
I am getting the same too. Latest harbot on k8s:

docker login xxxx.xxxxx.com
Username: homer
Password: 
Error response from daemon: Get https://xxxx.xxxxx.com/v2/: Get xxx.xxxxx/service/token?account=homer&client_id=docker&offline_token=true&service=harbor-registry: unsupported protocol scheme ""

**Comment by apannwitz** [comment]
Hi,

sorry, yes, I fix it by myself. I deployed via helm with parameter 

"--set externalURL=xxx.yyy.com"

but this was wrong! For me it should be 

"--set externalURL=https://xxx.yyy.com"

I hope this helps.
